"""lys-best as a single free-floating chain at 280 K, CALVADOS-TEA on.

Sequence is lysarr12-even-4 verbatim. Generated by tools/tea_pairs.py — edit the
driver, not this file.

Free solution is CALVADOS's own default: topol 'center' puts the one molecule
at the box centre, ext_force is false so there is no wall, and residue 0 is an
ordinary residue, not the "Z" anchor.

The box is 60 nm, not the 35 nm of the earlier free-chain sweep — those chains
were within the nonbonded cutoff of their own periodic image in most frames.
"""

import os
from pathlib import Path

from calvados.cfg import Config, Components
from calvados.sim import Sim

from tools.paths import ensure_runtime_dir
from tools.metadata import write_metadata
from tools.tea import report as tea_report, write_residues_csv

sim_name = Path(__file__).parent.name

sequence = "HHHHHHVPGIGVPGIGVPGIGVPGIGVPGIGVPGKGVPGIGVPGIGVPGIGVPGIGVPGIGRGDVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGMGVPGIGVPGKGVPGIGRGDVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGRGDVPGIGVPGKGVPGIGVPGIGVPGMGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGRGDVPGIGVPGIGVPGIGVPGIGVPGIGVPGKGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIG"
temperature = 280.0
gamma = 3.0
box_side = 60.0
N_save = 7000
N_frames = 4286
seed = 20261008


def build_sim(sim: Sim):
    """CALVADOS centres the single chain itself."""
    return


if __name__ == "__main__":
    path = Path(__file__).parent.resolve()
    cwd = Path(os.getcwd())
    runtime_dir = ensure_runtime_dir(path)
    fasta_file = runtime_dir / "molecules.fasta"

    # TEA: lambda at this run's temperature, written here and used only here.
    # residues_CALVADOS2.csv is read and never modified.
    fresidues = runtime_dir / "residues_TEA.csv"
    lambdas = write_residues_csv(fresidues, temperature, gamma,
                                 source=cwd / "residues_CALVADOS2.csv")
    (runtime_dir / "tea.yaml").write_text(
        "# CALVADOS-TEA, as this run used it. Read back by tools/metadata.py.\n"
        f"temperature_K: {temperature}\n"
        f"gamma: {gamma}\n"
        "T0_K: 300.0\n"
        "source_table: residues_CALVADOS2.csv\n"
        "lambdas:\n"
        + "".join(f"  {k}: {v!r}\n" for k, v in sorted(lambdas.items())))
    print(tea_report(temperature, gamma))

    config = Config(
        sysname = sim_name, box = [box_side, box_side, box_side],
        temp = temperature, ionic = 0.19, pH = 7.5,
        topol = 'center', ext_force = False,
        wfreq = N_save, steps = N_frames * N_save, runtime = 0,
        platform = 'CUDA', restart = 'checkpoint', frestart = 'restart.chk',
        random_number_seed = seed, verbose = True,
    )
    components = Components(
        molecule_type = 'protein', nmol = 1, restraint = False,
        charge_termini = 'both',
        fresidues = str(fresidues),
        ffasta = str(fasta_file),
    )
    components.add(name=sim_name)

    config.write(str(runtime_dir), "config.yaml")
    components.write(str(runtime_dir), "components.yaml")
    fasta_file.write_text(f">{sim_name}\n{sequence}")
    (runtime_dir / "run.py").write_text((cwd / "template/run.py").read_text())
    job = (cwd / "template/job.sh").read_text() \
        .replace("{sim_name}", sim_name).replace("{partition}", "gpu-a100") \
        .replace("{runtime}", "0:40:00").replace("{cpu_per_task}", "18")
    (runtime_dir / "job.sh").write_text(job)
    write_metadata(runtime_dir)
