"""Best/worst pairs x {280, 350} K x {brush, free solution}, with CALVADOS-TEA on.

    .venv/bin/python tools/tea_pairs.py plan
    .venv/bin/python tools/tea_pairs.py init
    .venv/bin/python tools/tea_pairs.py submit --yes

16 runs: four sequences, two temperatures, two geometries. The point is the
280 -> 350 K comparison *within* each sequence and geometry, which is why both
temperatures use the same seed per cell - the pair differs only in lambda(T)
and kT.

Sequences
---------
Lysine arrangement, ranked by inter-chain share of crosslink hits
(lysine-arrangement-results.xlsx): best lysarr12-even-4 (0.870), worst
lysarr02-blk4-mid (0.0064).

RGD arrangement, ranked by the 23-mer SASA across all 24 free-chain runs
(sasa-24-arrangements.csv): best 19-3n-1c (82.11 nm2), worst 16-pairs-mid
(80.73). That is the ranking with a resolvable signal and a known mechanism
(copies at a chain end); the Rg ranking over the same 24 is sampling noise.

Box size, free runs
-------------------
60 nm, not the 35 nm the free-rgdarr sweep used. Those chains reached past half
their box in 20-26% of frames and within the 4 nm cutoff of their own image in
59-67%, so they were self-interacting. At 280 K with TEA the chain is more
expanded than any of them, which would make it worse. 60 nm clears 2 x the
measured p99 extent plus the cutoff. It costs almost nothing - the neighbour
list scales with beads, not volume - but it does mean absolute Rg here is not
directly comparable with the 35 nm runs.
"""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

from tools.new_simulation import _project_root, create_simulation
from tools.tea import T_MAX, T_MIN

GAMMA = 3.0
TEMPERATURES = [280.0, 350.0]      # 280 is exactly TEA's lower fit bound
NS = 300.0
N_SAVE = 7000                      # 70 ps/frame, same cadence as the sweeps
N_FRAMES = int(round(NS * 1000.0 / (N_SAVE * 0.01)))   # 4286 -> 300.02 ns

# Brush: as the originals were run, so the geometry is the familiar one.
BRUSH_CONCENTRATION = 0.04
BRUSH_NMOL = 16
FREE_BOX_NM = 60.0

# Measured on this hardware: 16-chain runs at 0.04 chains/nm2 did 400 ns/h
# (lysarr12 407.7, rgdarr19 402.9), a single free chain 975 ns/h. 300 ns is
# therefore ~45 min grafted and ~19 min free. These requests are ~1.7x and
# ~2.1x that - enough headroom to survive a slow node, small enough to backfill
# quickly, which matters with the cluster going down tomorrow.
BRUSH_WALLTIME = "1:15:00"
FREE_WALLTIME = "0:40:00"
PARTITION = "gpu-a100"
CPUS = "18"
SEED0 = 20261003

SOURCES = {
    "lys-best": "lysarr12-even-4",
    "lys-worst": "lysarr02-blk4-mid",
    "rgd-best": "free-rgdarr19-3n-1c",
    "rgd-worst": "free-rgdarr16-pairs-mid",
}

FREE_PREPARE = '''"""{label} as a single free-floating chain at {temperature:g} K, CALVADOS-TEA on.

Sequence is {source} verbatim. Generated by tools/tea_pairs.py — edit the
driver, not this file.

Free solution is CALVADOS's own default: topol 'center' puts the one molecule
at the box centre, ext_force is false so there is no wall, and residue 0 is an
ordinary residue, not the "Z" anchor.

The box is 60 nm, not the 35 nm of the earlier free-chain sweep — those chains
were within the nonbonded cutoff of their own periodic image in most frames.
"""

import os
from pathlib import Path

from calvados.cfg import Config, Components
from calvados.sim import Sim

from tools.paths import ensure_runtime_dir
from tools.metadata import write_metadata
from tools.tea import report as tea_report, write_residues_csv

sim_name = Path(__file__).parent.name

sequence = "{sequence}"
temperature = {temperature!r}
gamma = {gamma!r}
box_side = {box!r}
N_save = {n_save}
N_frames = {n_frames}
seed = {seed}


def build_sim(sim: Sim):
    """CALVADOS centres the single chain itself."""
    return


if __name__ == "__main__":
    path = Path(__file__).parent.resolve()
    cwd = Path(os.getcwd())
    runtime_dir = ensure_runtime_dir(path)
    fasta_file = runtime_dir / "molecules.fasta"

    # TEA: lambda at this run's temperature, written here and used only here.
    # residues_CALVADOS2.csv is read and never modified.
    fresidues = runtime_dir / "residues_TEA.csv"
    lambdas = write_residues_csv(fresidues, temperature, gamma,
                                 source=cwd / "residues_CALVADOS2.csv")
    (runtime_dir / "tea.yaml").write_text(
        "# CALVADOS-TEA, as this run used it. Read back by tools/metadata.py.\\n"
        f"temperature_K: {{temperature}}\\n"
        f"gamma: {{gamma}}\\n"
        "T0_K: 300.0\\n"
        "source_table: residues_CALVADOS2.csv\\n"
        "lambdas:\\n"
        + "".join(f"  {{k}}: {{v!r}}\\n" for k, v in sorted(lambdas.items())))
    print(tea_report(temperature, gamma))

    config = Config(
        sysname = sim_name, box = [box_side, box_side, box_side],
        temp = temperature, ionic = 0.19, pH = 7.5,
        topol = 'center', ext_force = False,
        wfreq = N_save, steps = N_frames * N_save, runtime = 0,
        platform = 'CUDA', restart = 'checkpoint', frestart = 'restart.chk',
        random_number_seed = seed, verbose = True,
    )
    components = Components(
        molecule_type = 'protein', nmol = 1, restraint = False,
        charge_termini = 'both',
        fresidues = str(fresidues),
        ffasta = str(fasta_file),
    )
    components.add(name=sim_name)

    config.write(str(runtime_dir), "config.yaml")
    components.write(str(runtime_dir), "components.yaml")
    fasta_file.write_text(f">{{sim_name}}\\n{{sequence}}")
    (runtime_dir / "run.py").write_text((cwd / "template/run.py").read_text())
    job = (cwd / "template/job.sh").read_text() \\
        .replace("{{sim_name}}", sim_name).replace("{{partition}}", "{partition}") \\
        .replace("{{runtime}}", "{walltime}").replace("{{cpu_per_task}}", "{cpus}")
    (runtime_dir / "job.sh").write_text(job)
    write_metadata(runtime_dir)
'''


def source_sequence(name: str) -> str:
    """The sequence as the source run defines it, untagged (no "Z")."""
    import re

    text = (Path("simulations") / name / "prepare.py").read_text()
    match = re.search(r'"([ACDEFGHIKLMNPQRSTVWYZ]{50,})"', text)
    if not match:
        raise ValueError(f"no sequence found in simulations/{name}/prepare.py")
    seq = match.group(1)
    return seq[1:] if seq.startswith("Z") else seq


def cells() -> list[dict]:
    out = []
    for s_index, (label, source) in enumerate(sorted(SOURCES.items())):
        for t_index, temperature in enumerate(TEMPERATURES):
            for geometry in ("brush", "free"):
                out.append({
                    "name": f"tea-{label}-{geometry}-{int(temperature)}k",
                    "label": label, "source": source, "geometry": geometry,
                    "temperature": temperature,
                    # Same seed for both temperatures of a cell: the pair then
                    # differs only in lambda(T) and kT, not in its draw.
                    "seed": SEED0 + s_index * 10 + (0 if geometry == "brush" else 5),
                })
    return out


def init(root: Path, dry_run: bool = False) -> list[dict]:
    for T in TEMPERATURES:
        if not T_MIN <= T <= T_MAX:
            raise ValueError(f"{T} K is outside TEA's {T_MIN:g}-{T_MAX:g} K range")
    made = cells()
    if dry_run:
        return made

    for cell in made:
        sequence = source_sequence(cell["source"])
        sim_dir = root / "simulations" / cell["name"]
        if cell["geometry"] == "brush":
            create_simulation(
                sequence=sequence,
                concentration=BRUSH_CONCENTRATION,
                nmol=BRUSH_NMOL,
                steps=N_SAVE * N_FRAMES,
                name=cell["name"],
                temperature=cell["temperature"],
                tea=True,
                tea_gamma=GAMMA,
                mode="brush",
                platform="CUDA",
                partition=PARTITION,
                walltime=BRUSH_WALLTIME,
                cpu_per_task=CPUS,
            )
        else:
            sim_dir.mkdir(parents=True, exist_ok=True)
            (sim_dir / "prepare.py").write_text(FREE_PREPARE.format(
                label=cell["label"], source=cell["source"], sequence=sequence,
                temperature=cell["temperature"], gamma=GAMMA, box=FREE_BOX_NM,
                n_save=N_SAVE, n_frames=N_FRAMES, seed=cell["seed"],
                partition=PARTITION, walltime=FREE_WALLTIME, cpus=CPUS))
        cell["n_residues"] = len(sequence)
    return made


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=["plan", "init", "submit", "status"])
    parser.add_argument("--yes", action="store_true")
    args = parser.parse_args(argv)
    root = _project_root()

    if args.command in ("plan", "status"):
        made = cells()
        print(f"{len(made)} runs — {len(SOURCES)} sequences x {len(TEMPERATURES)} "
              f"temperatures x 2 geometries, {NS:g} ns each, TEA on (gamma {GAMMA:g})")
        for cell in made:
            runtime = root / "simulations" / cell["name"] / "runtime"
            state = ""
            if args.command == "status":
                meta = runtime / "metadata.csv"
                state = "not prepared"
                if meta.is_file():
                    rows = dict(l.split(",")[:2] for l in meta.read_text().splitlines()[1:]
                                if "," in l)
                    state = rows.get("status", "prepared")
            print(f"  {cell['name']:<30} {cell['source']:<24} "
                  f"{cell['geometry']:<6} {cell['temperature']:>5.0f} K  {state}")
        if args.command == "plan":
            brush = sum(1 for c in made if c["geometry"] == "brush")
            print(f"\nwalltime: {brush} brush x {BRUSH_WALLTIME} + {len(made)-brush} free "
                  f"x {FREE_WALLTIME}")
            print(f"measured rates: 400 ns/h grafted, 975 ns/h free -> "
                  f"~45 min and ~19 min actual")
        return 0

    if args.command == "init":
        made = init(root)
        print(f"\nprepared {len(made)} runs")
        return 0

    made = cells()
    missing = [c["name"] for c in made
               if not (root / "simulations" / c["name"] / "runtime" / "job.sh").is_file()]
    if missing:
        print(f"{len(missing)} run(s) have no runtime/job.sh — run `init` first, and "
              f"`sim prepare <name>` for the free ones:")
        for name in missing[:6]:
            print(f"  {name}")
        return 1
    if not args.yes:
        print(f"would sbatch {len(made)} jobs; re-run with --yes")
        return 0
    for cell in made:
        subprocess.run(["sbatch", str(root / "simulations" / cell["name"]
                                      / "runtime" / "job.sh")], cwd=root, check=False)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
