"""270 / 350 K single-chain set, plus the no-TEA controls for the 280/350 K runs.

    .venv/bin/python tools/tea_temps.py plan
    .venv/bin/python tools/tea_temps.py init
    .venv/bin/python tools/tea_temps.py submit --yes --group controls

58 runs, all single free chains:

  4   controls      350 K, TEA OFF, the four sequences of the 280/350 K set.
                    Isolates lambda(T) from kT: these differ from
                    tea-*-free-350k in exactly one thing, so if the LCST
                    collapse is the stickiness and not the thermostat, these
                    stay expanded.
  2   vpgig         (VPGIG)71 + VP, 500 ns, 270 and 350 K. Bare ELP baseline.
  2   orig          the 357-aa original RGD construct, 270 and 350 K.
  2   allterm       every RGD block and lysine at the termini, 270 and 350 K.
  48  rgdarr01..24  the 24 arrangements again, 270 and 350 K.

270 K is EXTRAPOLATION
----------------------
TEA's hydration fits run 280-380 K. 270 K is 10 K below that and below the
freezing point of bulk water, so no data constrains lambda there. The numbers
are a smooth continuation of eq 2, not a prediction: lambda(I) 0.3618 -> 0.2546,
lambda(V) 0.1112 -> 0.0549, no sign flips. Every run asks for this in writing
via allow_extrapolation and records it in runtime/tea.yaml, and tools/tea.py
still refuses by default so no ordinary run can drift out there by accident.

Box
---
80 nm, up from the 60 nm of the 280/350 K set. At 280 K the chain already used
32 nm of extent and 2.1% of frames came within the cutoff of its own image; 270 K
is more expanded still. Both legs share the box so it is not a variable. The
controls stay at 60 nm, because a control must differ from what it controls in
one thing only.
"""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

from tools.new_simulation import _project_root
from tools.tea_sequences import all_terminal, original, vpgig_only

GAMMA = 3.0
TEMPERATURES = [270.0, 350.0]
CONTROL_T = 350.0

N_SAVE = 7000                      # 70 ps/frame, as the 280/350 K set used
NS_DEFAULT = 300.0
NS_VPGIG = 500.0

BOX_NM = 80.0                      # the 270/350 K set
CONTROL_BOX_NM = 60.0              # must match the runs it controls
CONTROL_NS = 300.0

# Measured: a single free chain of this length did 969-1174 ns/h on an A100
# (the 8 free runs of the 280/350 K set, 920-1115 s for 300.02 ns). 300 ns is
# ~19 min and 500 ns ~31 min at the slow end. Requests are deliberately tight:
# the maintenance reservation starts 2026-10-03T00:00 and Slurm will not start
# a job that cannot finish before it, so a short request keeps being schedulable
# for longer than a padded one.
WALLTIME_300 = "0:30:00"
WALLTIME_500 = "0:45:00"
PARTITION = "gpu-a100"
CPUS = "18"
SEED0 = 20261002

# A control must differ from the run it controls in ONE thing, so each one
# reuses that run's seed as well as its sequence: same draw, same thermostat,
# stock lambda instead of lambda(T). The seeds are read from the prepared
# config.yaml rather than copied here, so they cannot drift apart.
CONTROL_SOURCES = {
    "lys-best": "tea-lys-best-free-350k",
    "lys-worst": "tea-lys-worst-free-350k",
    "rgd-best": "tea-rgd-best-free-350k",
    "rgd-worst": "tea-rgd-worst-free-350k",
}


def _seed_of(sim_name: str, root: Path) -> int:
    """The seed a prepared run used, from its own config.yaml."""
    config = root / "simulations" / sim_name / "runtime" / "config.yaml"
    for line in config.read_text().splitlines():
        if line.strip().startswith("random_number_seed:"):
            return int(line.split(":", 1)[1])
    raise ValueError(f"no random_number_seed in {config}")

PREPARE = '''"""{title}

Single free chain, {temperature:g} K, {ns:g} ns. {tea_line}

Generated by tools/tea_sequences.py + tools/tea_temps.py — edit the drivers,
not this file.
"""

import os
from pathlib import Path

from calvados.cfg import Config, Components
from calvados.sim import Sim

from tools.paths import ensure_runtime_dir
from tools.metadata import write_metadata

sim_name = Path(__file__).parent.name

sequence = "{sequence}"
temperature = {temperature!r}
gamma = {gamma!r}
tea = {tea!r}
extrapolate = {extrapolate!r}
box_side = {box!r}
N_save = {n_save}
N_frames = {n_frames}
seed = {seed}


def build_sim(sim: Sim):
    """CALVADOS centres the single chain itself."""
    return


if __name__ == "__main__":
    path = Path(__file__).parent.resolve()
    cwd = Path(os.getcwd())
    runtime_dir = ensure_runtime_dir(path)
    fasta_file = runtime_dir / "molecules.fasta"

    # With tea False this is the line it always was: the project's own table,
    # read and never written. With tea True a table for THIS temperature is
    # written into runtime/ and used only here.
    fresidues = cwd / "residues_CALVADOS2.csv"
    if tea:
        from tools.tea import T_MAX, T_MIN, report as tea_report, write_residues_csv
        fresidues = runtime_dir / "residues_TEA.csv"
        # `extrapolate` is permission; this is whether it was actually used.
        outside = not T_MIN <= temperature <= T_MAX
        lambdas = write_residues_csv(fresidues, temperature, gamma,
                                     source=cwd / "residues_CALVADOS2.csv",
                                     allow_extrapolation=extrapolate)
        (runtime_dir / "tea.yaml").write_text(
            "# CALVADOS-TEA, as this run used it. Read back by tools/metadata.py.\\n"
            f"temperature_K: {{temperature}}\\n"
            f"gamma: {{gamma}}\\n"
            "T0_K: 300.0\\n"
            f"extrapolated_outside_fit_range: {{str(outside).lower()}}\\n"
            f"extrapolation_permitted: {{str(extrapolate).lower()}}\\n"
            f"fit_range_K: {{T_MIN:g}}-{{T_MAX:g}}\\n"
            "source_table: residues_CALVADOS2.csv\\n"
            "lambdas:\\n"
            + "".join(f"  {{k}}: {{v!r}}\\n" for k, v in sorted(lambdas.items())))
        print(tea_report(temperature, gamma, allow_extrapolation=extrapolate))
    else:
        print(f"TEA off: stock residues_CALVADOS2.csv at {{temperature:g}} K")

    config = Config(
        sysname = sim_name, box = [box_side, box_side, box_side],
        temp = temperature, ionic = 0.19, pH = 7.5,
        topol = 'center', ext_force = False,
        wfreq = N_save, steps = N_frames * N_save, runtime = 0,
        platform = 'CUDA', restart = 'checkpoint', frestart = 'restart.chk',
        random_number_seed = seed, verbose = True,
    )
    components = Components(
        molecule_type = 'protein', nmol = 1, restraint = False,
        charge_termini = 'both',
        fresidues = str(fresidues),
        ffasta = str(fasta_file),
    )
    components.add(name=sim_name)

    config.write(str(runtime_dir), "config.yaml")
    components.write(str(runtime_dir), "components.yaml")
    fasta_file.write_text(f">{{sim_name}}\\n{{sequence}}")
    (runtime_dir / "run.py").write_text((cwd / "template/run.py").read_text())
    job = (cwd / "template/job.sh").read_text() \\
        .replace("{{sim_name}}", sim_name).replace("{{partition}}", "{partition}") \\
        .replace("{{runtime}}", "{walltime}").replace("{{cpu_per_task}}", "{cpus}")
    (runtime_dir / "job.sh").write_text(job)
    write_metadata(runtime_dir)
'''


def _sequence_of(sim_name: str, root: Path) -> str:
    """The sequence a prepared run uses, from its fasta if it has one."""
    fasta = root / "simulations" / sim_name / "runtime" / "molecules.fasta"
    if fasta.is_file():
        return "".join(fasta.read_text().splitlines()[1:]).strip()
    text = (root / "simulations" / sim_name / "prepare.py").read_text()
    seq = re.search(r'"([ACDEFGHIKLMNPQRSTVWYZ]{50,})"', text).group(1)
    return seq[1:] if seq.startswith("Z") else seq


def arrangements(root: Path) -> list[tuple[str, str]]:
    """(short label, source run) for the 24 free RGD arrangements, in order."""
    out = []
    for path in sorted((root / "simulations").glob("free-rgdarr*")):
        if path.name.endswith("-500ns"):
            continue            # a longer rerun of a sequence already in the set
        out.append((path.name.replace("free-rgdarr", "rgd"), path.name))
    if len(out) != 24:
        raise ValueError(f"expected 24 arrangements, found {len(out)}")
    return out


def cells(root: Path) -> list[dict]:
    out = []

    for i, (label, source) in enumerate(sorted(CONTROL_SOURCES.items())):
        out.append({
            "group": "controls", "name": f"ctrl-{label}-free-350k-notea",
            "title": f"No-TEA control for tea-{label}-free-350k.",
            "source": source, "tea": False, "extrapolate": False,
            "temperature": CONTROL_T, "ns": CONTROL_NS, "box": CONTROL_BOX_NM,
            "seed": _seed_of(source, root),
        })

    designed = [
        ("vpgig", "Bare ELP baseline: (VPGIG)71 + VP, no RGD and no lysine.",
         vpgig_only(root), NS_VPGIG),
        ("orig", "The 357-aa original RGD construct, verbatim.",
         original(root), NS_DEFAULT),
        ("allterm", "Original composition, every RGD block and lysine at the termini.",
         all_terminal(root), NS_DEFAULT),
    ]
    for i, (label, title, sequence, ns) in enumerate(designed):
        for j, T in enumerate(TEMPERATURES):
            out.append({
                "group": "designed", "name": f"tt-{label}-{int(T)}k", "title": title,
                "sequence": sequence, "tea": True, "extrapolate": True,
                "temperature": T, "ns": ns, "box": BOX_NM,
                "seed": SEED0 + 200 + i * 10 + j,
            })

    for i, (label, source) in enumerate(arrangements(root)):
        for j, T in enumerate(TEMPERATURES):
            out.append({
                "group": "arrangements", "name": f"tt-{label}-{int(T)}k",
                "title": f"RGD arrangement {label}, sequence from {source}.",
                "source": source, "tea": True, "extrapolate": True,
                "temperature": T, "ns": NS_DEFAULT, "box": BOX_NM,
                "seed": SEED0 + 1000 + i * 10 + j,
            })
    return out


def init(root: Path, groups: list[str] | None = None) -> list[dict]:
    made = [c for c in cells(root) if not groups or c["group"] in groups]
    for cell in made:
        sequence = cell.get("sequence") or _sequence_of(cell["source"], root)
        n_frames = int(round(cell["ns"] * 1000.0 / (N_SAVE * 0.01)))
        sim_dir = root / "simulations" / cell["name"]
        sim_dir.mkdir(parents=True, exist_ok=True)
        tea_line = (f"CALVADOS-TEA on, gamma {GAMMA:g}"
                    + (" — EXTRAPOLATED below the 280 K fit bound."
                       if cell["extrapolate"] and cell["temperature"] < 280.0 else ".")
                    ) if cell["tea"] else "TEA off (stock CALVADOS 2 lambda)."
        (sim_dir / "prepare.py").write_text(PREPARE.format(
            title=cell["title"], sequence=sequence, temperature=cell["temperature"],
            gamma=GAMMA, tea=cell["tea"], extrapolate=cell["extrapolate"],
            box=cell["box"], n_save=N_SAVE, n_frames=n_frames, seed=cell["seed"],
            ns=cell["ns"], tea_line=tea_line, partition=PARTITION,
            walltime=WALLTIME_500 if cell["ns"] > 400 else WALLTIME_300, cpus=CPUS))
        cell["n_residues"] = len(sequence)
        cell["n_frames"] = n_frames
    return made


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=["plan", "init", "submit", "status"])
    parser.add_argument("--group", action="append",
                        choices=["controls", "designed", "arrangements"],
                        help="limit to these groups (default: all)")
    parser.add_argument("--yes", action="store_true")
    args = parser.parse_args(argv)
    root = _project_root()
    made = [c for c in cells(root) if not args.group or c["group"] in args.group]

    if args.command in ("plan", "status"):
        print(f"{len(made)} runs, all single free chains")
        for cell in made:
            state = ""
            if args.command == "status":
                job = root / "simulations" / cell["name"] / "runtime" / "job.sh"
                state = "prepared" if job.is_file() else "not prepared"
            tea = f"TEA {GAMMA:g}" + ("*" if cell["extrapolate"]
                                      and cell["temperature"] < 280.0 else "") \
                if cell["tea"] else "no TEA"
            print(f"  {cell['name']:<32}{cell['group']:<14}{cell['temperature']:>5.0f} K"
                  f"{cell['ns']:>7.0f} ns  {cell['box']:>4.0f} nm  {tea:<9}{state}")
        if args.command == "plan":
            print("\n* = lambda extrapolated below TEA's 280 K fit bound")
            hours = sum(c["ns"] / 969.0 for c in made)
            print(f"measured 969-1174 ns/h -> ~{hours:.1f} GPU-hours of actual compute")
        return 0

    if args.command == "init":
        made = init(root, args.group)
        print(f"prepared {len(made)} runs")
        return 0

    missing = [c["name"] for c in made
               if not (root / "simulations" / c["name"] / "runtime" / "job.sh").is_file()]
    if missing:
        print(f"{len(missing)} run(s) have no runtime/job.sh — `init` then `sim prepare`:")
        for name in missing[:6]:
            print(f"  {name}")
        return 1
    if not args.yes:
        print(f"would sbatch {len(made)} jobs; re-run with --yes")
        return 0
    for cell in made:
        subprocess.run(["sbatch", str(root / "simulations" / cell["name"]
                                      / "runtime" / "job.sh")], cwd=root, check=False)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
