"""RGD arrangement rgd14-tight-c, sequence from free-rgdarr14-tight-c.

Single free chain, 270 K, 300 ns. CALVADOS-TEA on, gamma 3 — EXTRAPOLATED below the 280 K fit bound.

Generated by tools/tea_sequences.py + tools/tea_temps.py — edit the drivers,
not this file.
"""

import os
from pathlib import Path

from calvados.cfg import Config, Components
from calvados.sim import Sim

from tools.paths import ensure_runtime_dir
from tools.metadata import write_metadata

sim_name = Path(__file__).parent.name

sequence = "LQVPGIGVPGIGVPGKGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGKGVPGIGVPGIGVPGMGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGKGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPGIGVPLDASTVYAVTGRGDSPASSAASAVPGKGVPGIGVPGIGVPLDASTVYAVTGRGDSPASSAASAVPGMGVPGIGVPGIGVPLDASTVYAVTGRGDSPASSAASAVPGIGVPGIGVPGIGVPLDASTVYAVTGRGDSPASSAASA"
temperature = 270.0
gamma = 3.0
tea = True
extrapolate = True
box_side = 80.0
N_save = 7000
N_frames = 4286
seed = 20262132


def build_sim(sim: Sim):
    """CALVADOS centres the single chain itself."""
    return


if __name__ == "__main__":
    path = Path(__file__).parent.resolve()
    cwd = Path(os.getcwd())
    runtime_dir = ensure_runtime_dir(path)
    fasta_file = runtime_dir / "molecules.fasta"

    # With tea False this is the line it always was: the project's own table,
    # read and never written. With tea True a table for THIS temperature is
    # written into runtime/ and used only here.
    fresidues = cwd / "residues_CALVADOS2.csv"
    if tea:
        from tools.tea import report as tea_report, write_residues_csv
        fresidues = runtime_dir / "residues_TEA.csv"
        lambdas = write_residues_csv(fresidues, temperature, gamma,
                                     source=cwd / "residues_CALVADOS2.csv",
                                     allow_extrapolation=extrapolate)
        (runtime_dir / "tea.yaml").write_text(
            "# CALVADOS-TEA, as this run used it. Read back by tools/metadata.py.\n"
            f"temperature_K: {temperature}\n"
            f"gamma: {gamma}\n"
            "T0_K: 300.0\n"
            f"extrapolated_outside_fit_range: {str(extrapolate).lower()}\n"
            "fit_range_K: 280.0-380.0\n"
            "source_table: residues_CALVADOS2.csv\n"
            "lambdas:\n"
            + "".join(f"  {k}: {v!r}\n" for k, v in sorted(lambdas.items())))
        print(tea_report(temperature, gamma, allow_extrapolation=extrapolate))
    else:
        print(f"TEA off: stock residues_CALVADOS2.csv at {temperature:g} K")

    config = Config(
        sysname = sim_name, box = [box_side, box_side, box_side],
        temp = temperature, ionic = 0.19, pH = 7.5,
        topol = 'center', ext_force = False,
        wfreq = N_save, steps = N_frames * N_save, runtime = 0,
        platform = 'CUDA', restart = 'checkpoint', frestart = 'restart.chk',
        random_number_seed = seed, verbose = True,
    )
    components = Components(
        molecule_type = 'protein', nmol = 1, restraint = False,
        charge_termini = 'both',
        fresidues = str(fresidues),
        ffasta = str(fasta_file),
    )
    components.add(name=sim_name)

    config.write(str(runtime_dir), "config.yaml")
    components.write(str(runtime_dir), "components.yaml")
    fasta_file.write_text(f">{sim_name}\n{sequence}")
    (runtime_dir / "run.py").write_text((cwd / "template/run.py").read_text())
    job = (cwd / "template/job.sh").read_text() \
        .replace("{sim_name}", sim_name).replace("{partition}", "gpu-a100") \
        .replace("{runtime}", "0:30:00").replace("{cpu_per_task}", "18")
    (runtime_dir / "job.sh").write_text(job)
    write_metadata(runtime_dir)
